stages:
  - build

build-and-push:
  stage: build
  image:
    name: registry.gitlab.com/testifysec/docker-images/ko:0.9.3
    entrypoint: [""]
  script:
    - cd ${CI_PROJECT_DIR}/cmd/rekor-server
    - ko auth login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - KO_DOCKER_REPO=${CI_REGISTRY}/testifysec/rekor ko publish --tarball ${CI_PROJECT_DIR}/rekor-server.${CI_COMMIT_TAG}.tar .
  rules:
      - if: $CI_COMMIT_TAG
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/rekor-server.${CI_COMMIT_TAG}.tar
  rules:
    - if: $CI_COMMIT_TAG